import { StyleSheet } from 'react-native';

import { BottomTabInset, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  drawerTrack: {
    flex: 1,
    flexDirection: 'row',
  },
  drawerPane: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    position: 'relative',
  },
  profileButton: {
    position: 'absolute',
    right: Spacing.two,
    zIndex: 30,
    alignItems: 'center',
  },
  sessionsButtonFrame: {
    position: 'absolute',
    left: Spacing.two,
    zIndex: 40,
  },
  sessionsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#c8d8d0',
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  sessionsButtonLine: {
    width: 21,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#426256',
  },
  pressedControl: {
    opacity: 0.68,
  },
  profileGlass: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
  },
  profileAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileText: {
    color: '#3f7354',
    fontSize: 13,
    lineHeight: 16,
    fontWeight: '800',
    letterSpacing: 0,
  },
  transcriptCard: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
  },
  chatScroll: {
    flex: 1,
  },
  chatStack: {
    flexGrow: 1,
    justifyContent: 'flex-end',
    gap: 12,
  },
  userBubble: {
    alignSelf: 'flex-end',
    borderRadius: 8,
    backgroundColor: '#eef6f4',
  },
  assistantMessageRow: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    minWidth: 84,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4e9e7',
  },
  assistantBubbleInRow: {
    flexShrink: 1,
  },
  chatLabel: {
    color: '#5f746e',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0,
    marginBottom: 4,
  },
  assistantAudioButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
    marginRight: Spacing.two,
    overflow: 'hidden',
  },
  assistantAvatarSpacer: {
    width: 36,
    height: 36,
    marginTop: 2,
    marginRight: Spacing.two,
  },
  assistantStatusAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginTop: 2,
    marginRight: Spacing.two,
    overflow: 'hidden',
  },
  assistantAudioGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  assistantAudioPlayIcon: {
    width: 0,
    height: 0,
    marginLeft: 2,
    borderTopWidth: 7,
    borderBottomWidth: 7,
    borderLeftWidth: 11,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderLeftColor: '#ffffff',
  },
  assistantAudioStopIcon: {
    width: 12,
    height: 12,
    borderRadius: 2,
    backgroundColor: '#ffffff',
  },
  transcriptText: {
    color: '#24312e',
    fontSize: 18,
    lineHeight: 26,
    letterSpacing: 0,
  },
  medicineCards: {
    gap: Spacing.two,
    marginTop: Spacing.three,
  },
  medicineCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
    padding: Spacing.two,
    borderRadius: 8,
    backgroundColor: '#f5faf8',
    borderWidth: 1,
    borderColor: '#dce8e3',
  },
  medicineIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#d9efe6',
  },
  medicineIconText: {
    color: '#2f6b55',
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '800',
    letterSpacing: 0,
  },
  medicineCardText: {
    flex: 1,
  },
  medicineName: {
    color: '#1f312b',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  medicineLabel: {
    color: '#6d8178',
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0,
  },
  animatedTranscriptText: {
    position: 'relative',
  },
  hiddenTranscriptText: {
    opacity: 0,
  },
  visibleTranscriptText: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
  },
  listenArea: {
    position: 'absolute',
    bottom: BottomTabInset + Spacing.one,
    left: 0,
    right: 0,
    height: 96,
    paddingHorizontal: Spacing.four,
    alignItems: 'center',
    justifyContent: 'flex-start',
    zIndex: 30,
    elevation: 30,
  },
  listeningText: {
    position: 'absolute',
    top: 76,
    color: '#5f746e',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0,
  },
  sessionsScreen: {
    flex: 1,
    backgroundColor: '#f7faf8',
    paddingHorizontal: Spacing.four,
  },
  sessionsHeader: {
    paddingTop: Spacing.three,
    paddingBottom: Spacing.four,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: Spacing.three,
  },
  sessionsTitle: {
    color: '#17231f',
    fontSize: 32,
    lineHeight: 38,
    fontWeight: '800',
    letterSpacing: 0,
  },
  sessionsSubtitle: {
    color: '#6d8178',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  sessionsList: {
    flex: 1,
  },
  sessionsListContent: {
    paddingBottom: Spacing.six,
    gap: Spacing.three,
  },
  sessionItem: {
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e2ebe7',
    paddingHorizontal: Spacing.three,
    paddingVertical: Spacing.three,
  },
  sessionTitle: {
    color: '#17231f',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '800',
    letterSpacing: 0,
  },
  sessionPreview: {
    marginTop: 6,
    color: '#5f746e',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0,
  },
  sessionMeta: {
    marginTop: Spacing.two,
    color: '#8a9b95',
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0,
  },
  emptySessions: {
    minHeight: 260,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: Spacing.four,
  },
  emptySessionsTitle: {
    color: '#17231f',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0,
  },
  emptySessionsText: {
    marginTop: Spacing.two,
    color: '#6d8178',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
    letterSpacing: 0,
  },
});
