import { StyleSheet } from 'react-native';

import { Palette, Shadows, Spacing, Typography } from '@/constants/theme';

export const medicineStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Palette.screen,
  },
  safeArea: {
    flex: 1,
  },
  formBody: {
    flex: 1,
  },
  content: {
    paddingHorizontal: Spacing.three,
    paddingBottom: 96,
    gap: Spacing.three,
  },
  header: {
    paddingTop: Spacing.two,
    gap: Spacing.two,
  },
  schedulerTopBar: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
  },
  schedulerChatButton: {
    minHeight: 38,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.one,
    paddingHorizontal: Spacing.two,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
  },
  schedulerChatButtonText: {
    color: Palette.primary,
    ...Typography.label,
    fontWeight: '700',
  },
  calendarHeader: {
    paddingTop: Spacing.two,
    gap: Spacing.three,
  },
  calendarHeaderTop: {
    minHeight: 68,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.one,
  },
  calendarHeaderSide: {
    width: 82,
    minHeight: 44,
    justifyContent: 'center',
  },
  calendarTodayButton: {
    minHeight: 40,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingHorizontal: Spacing.one,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
  },
  pressedCalendarTodayButton: {
    opacity: 0.68,
  },
  calendarTodayButtonText: {
    color: Palette.primary,
    ...Typography.label,
    fontWeight: '700',
  },
  calendarTitleBlock: {
    flex: 1,
    alignItems: 'center',
  },
  calendarTitle: {
    color: Palette.ink,
    ...Typography.calendarTitle,
    lineHeight: 32,
    letterSpacing: 0,
    fontWeight: '800',
  },
  calendarDate: {
    color: Palette.inkSoft,
    ...Typography.control,
  },
  calendarGlyph: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
    ...Shadows.primarySoft,
  },
  calendarWeekFrame: {
    minHeight: 88,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  calendarWeekArrow: {
    width: 28,
    height: 34,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
  },
  pressedCalendarWeekArrow: {
    opacity: 0.68,
  },
  calendarWeekScroller: {
    flex: 1,
    minHeight: 88,
  },
  calendarWeekRow: {
    gap: 4,
    alignItems: 'center',
    paddingHorizontal: 0,
    paddingVertical: Spacing.two,
  },
  calendarDayButton: {
    width: 36,
    minHeight: 60,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  selectedCalendarDayButton: {
    backgroundColor: Palette.primary,
  },
  calendarDayName: {
    color: Palette.inkMuted,
    ...Typography.caption,
    fontWeight: '400',
  },
  calendarDayNumber: {
    color: Palette.ink,
    ...Typography.calendarNumber,
    fontWeight: '400',
  },
  selectedCalendarDayText: {
    color: Palette.white,
  },
  headerRow: {
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  title: {
    flex: 1,
    color: Palette.ink,
    ...Typography.screenTitle,
    fontWeight: '400',
  },
  listTitle: {
    flex: 1,
    color: Palette.ink,
    ...Typography.listTitle,
    fontWeight: '400',
    textAlign: 'center',
  },
  formTitle: {
    flex: 1,
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '400',
    textAlign: 'center',
  },
  subtitle: {
    color: Palette.textMuted,
    ...Typography.bodyRelaxed,
  },
  iconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
  },
  iconButtonSpacer: {
    width: 44,
    height: 44,
  },
  floatingAddButton: {
    position: 'absolute',
    right: Spacing.three,
    bottom: Spacing.three,
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primary,
    ...Shadows.floating,
  },
  primaryButton: {
    minHeight: 52,
    borderRadius: 8,
    paddingHorizontal: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primary,
  },
  primaryButtonText: {
    color: Palette.white,
    ...Typography.button,
    fontWeight: '400',
  },
  primaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  secondaryButton: {
    minHeight: 48,
    borderRadius: 8,
    paddingHorizontal: Spacing.three,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.borderMuted,
  },
  secondaryButtonText: {
    color: Palette.inkSoft,
    ...Typography.control,
    fontWeight: '400',
  },
  secondaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  card: {
    borderRadius: 8,
    padding: Spacing.three,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
    gap: Spacing.two,
  },
  scheduleCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  reminderSectionTitle: {
    color: Palette.ink,
    ...Typography.sectionTitle,
    fontWeight: '400',
    zIndex: 1,
  },
  reminderList: {
    marginTop: Spacing.two,
    gap: Spacing.two,
  },
  reminderCard: {
    borderRadius: 18,
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.two,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.reminderBorder,
    ...Shadows.cardSoft,
    gap: Spacing.two,
  },
  pressedReminderCard: {
    opacity: 0.78,
  },
  reminderCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  reminderTime: {
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '700',
  },
  reminderStatusCircle: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: Palette.neutralBorder,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
  },
  takenReminderStatusCircle: {
    backgroundColor: Palette.primary,
    borderColor: Palette.primary,
  },
  reminderCardBody: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  reminderMedicineIcon: {
    width: 46,
    height: 46,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primary,
  },
  reminderTextBlock: {
    flex: 1,
    gap: 5,
  },
  reminderNameRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    columnGap: 8,
    rowGap: 2,
  },
  reminderMedicineName: {
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '400',
  },
  reminderDoseText: {
    color: Palette.textDisabled,
    ...Typography.control,
  },
  reminderUnitsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 7,
  },
  reminderUnitsText: {
    color: Palette.inkMuted,
    ...Typography.label,
    fontWeight: '400',
  },
  reminderWarningText: {
    color: Palette.warningText,
    ...Typography.caption,
    fontWeight: '400',
  },
  reminderMetaSeparator: {
    color: Palette.textHint,
    ...Typography.meta,
  },
  reminderMetaText: {
    color: Palette.textMuted,
    ...Typography.meta,
  },
  medicineGlyph: {
    width: 42,
    height: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primaryTintSubtle,
  },
  medicineGlyphText: {
    color: Palette.primaryText,
    ...Typography.glyph,
    fontWeight: '400',
  },
  scheduleBody: {
    flex: 1,
    gap: 3,
  },
  scheduleName: {
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '400',
  },
  scheduleMeta: {
    color: Palette.textMuted,
    ...Typography.label,
  },
  scheduleDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  scheduleTime: {
    color: Palette.primary,
    ...Typography.bodySmall,
    fontWeight: '400',
  },
  scheduleTimePill: {
    minWidth: 72,
    minHeight: 34,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    backgroundColor: Palette.primarySoft,
    paddingHorizontal: Spacing.two,
  },
  stockWarningInline: {
    color: Palette.warningText,
    fontWeight: '400',
  },
  doseStatusRow: {
    flexDirection: 'row',
    gap: Spacing.one,
    paddingTop: 5,
  },
  doseStatusButton: {
    minHeight: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.two,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.inputBorder,
  },
  selectedDoseStatusButton: {
    backgroundColor: Palette.successSurface,
    borderColor: Palette.successBorder,
  },
  missedDoseStatusButton: {
    backgroundColor: Palette.dangerSurface,
    borderColor: Palette.dangerBorder,
  },
  doseStatusText: {
    color: Palette.textSubtle,
    ...Typography.caption,
    fontWeight: '400',
  },
  selectedDoseStatusText: {
    color: Palette.successText,
  },
  missedDoseStatusText: {
    color: Palette.dangerText,
  },
  empty: {
    minHeight: 220,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.one,
  },
  emptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primarySoft,
  },
  emptyTitle: {
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '400',
    textAlign: 'center',
  },
  emptyText: {
    color: Palette.textMuted,
    ...Typography.body,
    textAlign: 'center',
  },
  stepCaption: {
    color: Palette.textPlaceholder,
    ...Typography.label,
    textAlign: 'center',
    fontWeight: '400',
  },
  progressTrack: {
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.progressTrack,
    overflow: 'hidden',
  },
  progressFill: {
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.primary,
  },
  stepContent: {
    gap: Spacing.three,
  },
  sectionTitle: {
    color: Palette.ink,
    ...Typography.itemTitle,
    fontWeight: '400',
  },
  optionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.two,
  },
  medicineTypeScroller: {
    gap: 8,
    paddingHorizontal: 6,
    paddingVertical: 8,
    paddingRight: Spacing.three,
  },
  medicineTypeButton: {
    width: 78,
    minHeight: 68,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.border,
  },
  medicineTypeIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primaryTint,
  },
  selectedMedicineTypeIcon: {
    backgroundColor: Palette.primary,
  },
  selectedOptionText: {
    color: Palette.primary,
  },
  optionText: {
    color: Palette.inkSoft,
    ...Typography.caption,
    fontWeight: '400',
  },
  formGroup: {
    gap: 7,
  },
  label: {
    color: Palette.inkMuted,
    ...Typography.label,
    fontWeight: '400',
  },
  input: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Palette.inputBorder,
    backgroundColor: Palette.surface,
    paddingHorizontal: Spacing.three,
    color: Palette.ink,
    ...Typography.control,
  },
  inputHint: {
    color: Palette.textPlaceholder,
    ...Typography.caption,
  },
  inlineAction: {
    minHeight: 36,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingLeft: Spacing.two,
  },
  iconActionButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.dangerBorderSoft,
  },
  timePickerButton: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Palette.inputBorder,
    backgroundColor: Palette.surface,
    paddingHorizontal: Spacing.two,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  datePickerButton: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: Palette.inputBorder,
    backgroundColor: Palette.surface,
    paddingHorizontal: Spacing.two,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  timePickerIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primarySoft,
  },
  timePickerText: {
    flex: 1,
    color: Palette.ink,
    ...Typography.control,
    fontWeight: '400',
  },
  timePickerPlaceholder: {
    color: Palette.textHint,
  },
  row: {
    flexDirection: 'row',
    gap: Spacing.two,
  },
  rowItem: {
    flex: 1,
  },
  doseCard: {
    borderRadius: 8,
    backgroundColor: Palette.doseSurface,
    padding: Spacing.two,
    gap: Spacing.two,
  },
  doseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  doseTitle: {
    color: Palette.inkSoft,
    ...Typography.body,
    fontWeight: '400',
  },
  removeText: {
    color: Palette.danger,
    ...Typography.label,
    fontWeight: '400',
  },
  segmentedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.two,
  },
  segmentedButton: {
    flexBasis: '48%',
    flexGrow: 1,
    minHeight: 46,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.two,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.inputBorder,
  },
  selectedSegment: {
    backgroundColor: Palette.segmentSelected,
    borderColor: Palette.segmentSelected,
  },
  selectedSegmentText: {
    color: Palette.white,
  },
  reviewRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: Spacing.three,
    paddingVertical: Spacing.one,
  },
  reviewLabel: {
    flex: 1,
    color: Palette.textMuted,
    ...Typography.label,
  },
  reviewValue: {
    flex: 1.2,
    color: Palette.ink,
    ...Typography.body,
    fontWeight: '400',
    textAlign: 'right',
  },
  stockWarning: {
    minHeight: 44,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
    padding: Spacing.two,
    backgroundColor: Palette.warningSurface,
    borderWidth: 1,
    borderColor: Palette.warningBorder,
  },
  stockWarningText: {
    flex: 1,
    color: Palette.warningText,
    ...Typography.label,
    fontWeight: '400',
  },
  footer: {
    flexDirection: 'row',
    gap: Spacing.two,
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.two,
    backgroundColor: Palette.screen,
    borderTopWidth: 1,
    borderTopColor: Palette.border,
  },
  footerButton: {
    flex: 1,
    minHeight: 52,
  },
});
